import numpy as np
from PIL import Image
import os
from common import message_to_binary,encode_number ,generate_starting_points , binary_to_hex
from main_encrypt import dfs_encryption
from config import get_depth_limit, get_height, get_width, get_password
import subprocess


def get_Password(image_path, keyword, prime_number, random_number):
    """
    Generates a password based on the provided parameters.
    
    Args:
        image_path (str): Path to the input image
        keyword (str): User-provided keyword
        prime_number (int): Prime number chosen by user (19, 23, or 29)
        random_number (int): Random number less than 1000
        secret_message (str): The message to hide in the image
        
    Returns:
        str: Generated password
    """
    # Generate a password based on inputs
    # In a real implementation, this would be much more secure
    img = Image.open(image_path).convert("RGBA")
    width, height = img.size
    get_width(width)
    get_height(height)
    get_depth_limit(prime_number)
    get_password(keyword)
    while len(keyword) <15:
        keyword += "@"
    if len(keyword) >15:
        keyword = keyword[:15]

    start_points = generate_starting_points(width,height,random_number,50)
    start = start_points[0]

    My_password = encode_number(width) + encode_number(height)+ encode_number(prime_number)+ encode_number(start[0]) + encode_number(start[1])+ encode_number(random_number)+ message_to_binary(keyword)+"11111111111111111111111111111111"
    return binary_to_hex(My_password)

def encrypt_image(image_path, random_number,secret_message,output_path):
    print(f"encrypt_image called with: image_path={image_path}, random_number={random_number}")
    print(f"secret_message length: {len(secret_message)}, output_path: {output_path}")
    try:
        # Your existing code...
        img = Image.open(image_path).convert("RGBA")
        pixels = img.load()
        width, height = img.size
        start_points = generate_starting_points(width,height,random_number,50)
        print("Message Length",len(secret_message))
        visited = set()
        for coordinate in start_points:
            visited.add(coordinate)
        path = []
        enc_msg = message_to_binary(secret_message)
        i =0
        data_index = 0
        while True:
            start_x, start_y = start_points[i]
            next_start_x, next_start_y = start_points[i+1]
            next_point_binary = encode_number(next_start_x) + encode_number(next_start_y)
            enc_msg = enc_msg[:data_index]+next_point_binary+enc_msg[data_index:]
            data_index = dfs_encryption(start_x, start_y,False,enc_msg, pixels, visited, path, data_index)
            if data_index >= len(enc_msg):
                break
            i+=1

        # At the end, before returning:
        print(f"Saving image to {output_path}")
        img.save(output_path)
        
        # Verify the file was saved
        if os.path.exists(output_path):
            print(f"File saved successfully: {os.path.getsize(output_path)} bytes")
        else:
            print("WARNING: File was not saved!")
            
        return output_path
    except Exception as e:
        print(f"Exception in encrypt_image: {str(e)}")
        import traceback
        print(traceback.format_exc())
        raise     
   



def generate_python_file(keyword, prime_number, random_number, secret_message):
    """
    Generates a Python file that can be used to encode messages.
    
    Args:
        keyword (str): User-provided keyword
        prime_number (int): Prime number chosen by user
        random_number (int): Random number less than 1000
        secret_message (str): The message to hide
        
    Returns:
        str: Content of the Python file
    """
    code = f"""
# PixelPath Encoder - Generated File
# This file was generated by PixelPath for secure message transmission

import numpy as np
from PIL import Image
import sys
import os

def encode(image_path):
    # The encryption parameters were embedded in this file during generation
    keyword = "{keyword}"
    prime_number = {prime_number}
    random_number = {random_number}
    secret_message = "{secret_message}"
    
    try:
        # Load the image
        img = Image.open(image_path)
        pixels = np.array(img)
        
        # Generate output path
        filename = os.path.basename(image_path)
        name, ext = os.path.splitext(filename)
        output_path = os.path.join(os.path.dirname(image_path), f"encoded_{{name}}{{ext}}")
        
        # Password generation (this would be more secure in production)
        password = f"{{keyword}}-{{prime_number}}-{{random_number}}-{{hash(secret_message) % 10000:04d}}"
        
        print(f"Generated password: {{password}}")
        print(f"IMPORTANT: Keep this password secure! You'll need it to decrypt the message.")
        
        # Encode the message into the image
        # This is where your actual encoding algorithm would be
        
        # Save the encoded image
        img.save(output_path)
        print(f"Encoded image saved to: {{output_path}}")
        
        return True
    except Exception as e:
        print(f"Error: {{str(e)}}")
        return False

if __name__ == "__main__":
    if len(sys.argv) > 1:
        image_path = sys.argv[1]
        encode(image_path)
    else:
        print("Usage: python encoder.py <image_path>")
        print("This script will encode a secret message into the provided image.")
"""
    return code